remote_theme: just-the-docs/just-the-docs
title: DAW — Despliegue de Aplicaciones Web
description: Repositorio documental del módulo

url: "https://JoseAntonioGamez.github.io"
baseurl: "/DAW-Gamez-Garcia-Robles"

# Activa la navegación con desplegables
nav_enabled: true

# Ordenar la navegación por el campo "nav_order"
nav_sort: case_insensitive
nav_fold: true